(()=>{
const cv=document.getElementById('c'),ctx=cv.getContext('2d',{alpha:false}),$=id=>document.getElementById(id),MOBILE=/Android|iPhone|iPad|iPod|Mobile/i.test(navigator.userAgent);let W=0,H=0,dpr=1,U=1,R=12,last=performance.now(),audio=null;
const saved=JSON.parse(localStorage.getItem('neondodge_save')||'{}');const opt=Object.assign({master:.7,effects:.8,shake:true,motion:false,contrast:false,quality:MOBILE?'low':'high'},saved.opt||{});if(MOBILE&&opt.quality==='high')opt.quality='low';
const A={best:saved.best||0,bestTime:saved.bestTime||0,bestCombo:saved.bestCombo||0,totalEnergy:saved.totalEnergy||0,totalEnemies:saved.totalEnemies||0,games:saved.games||0,ach:saved.ach||{}};
const S={state:'menu',t:0,score:0,lives:3,combo:0,energy:0,enemies:0,inv:0,shake:0,phase:'TRAINING',event:'',eventT:0,eventNext:28,power:{shield:0,slow:0,magnet:0,boost:0,phase:0},spawnE:0,spawnN:2.7,spawnP:8,spawnM:0};let P={x:0,y:0,vx:0,vy:0,tx:undefined,ty:undefined},enemies=[],energy=[],powers=[],mines=[],parts=[],floats=[],trail=[],amb=[];
function save(){localStorage.setItem('neondodge_save',JSON.stringify({best:A.best,bestTime:A.bestTime,bestCombo:A.bestCombo,totalEnergy:A.totalEnergy,totalEnemies:A.totalEnemies,games:A.games,ach:A.ach,opt}))}function resize(){dpr=Math.min(devicePixelRatio||1,MOBILE?1:1.75);W=innerWidth;H=innerHeight;cv.width=W*dpr;cv.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);U=Math.max(.65,Math.min(1.35,Math.min(W,H)/600));R=Math.max(9,Math.min(14,Math.min(W,H)/38))}addEventListener('resize',resize);resize();for(let i=0;i<(opt.quality==='low'?18:opt.quality==='medium'?28:40);i++)amb.push({x:Math.random(),y:Math.random(),s:.2+Math.random()*.6,r:.5+Math.random()*1.5});
const keys={},map={KeyW:'u',ArrowUp:'u',KeyS:'d',ArrowDown:'d',KeyA:'l',ArrowLeft:'l',KeyD:'r'};addEventListener('keydown',e=>{if(map[e.code]){keys[map[e.code]]=1;e.preventDefault()}if(e.code==='KeyP'||e.code==='Escape')togglePause();if((e.code==='Enter'||e.code==='Space')&&S.state!=='play'&&S.state!=='pause'){if(S.state==='menu')start();else if(S.state==='over')start();e.preventDefault()}});addEventListener('keyup',e=>{if(map[e.code])keys[map[e.code]]=0});addEventListener('blur',()=>{Object.keys(keys).forEach(k=>keys[k]=0);if(S.state==='play')togglePause()});
let drag=null;cv.addEventListener('pointerdown',e=>{if(S.state!=='play')return;cv.setPointerCapture(e.pointerId);drag={id:e.pointerId};P.tx=e.clientX;P.ty=e.clientY;e.preventDefault()});cv.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;P.tx=e.clientX;P.ty=e.clientY;e.preventDefault()});['pointerup','pointercancel'].forEach(n=>cv.addEventListener(n,e=>{if(drag&&e.pointerId===drag.id){drag=null;P.tx=P.ty=undefined}}));
function sound(type){if(!opt.master||!opt.effects)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();let o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime,f={coin:520,hit:90,power:720,combo:980,phase:240,event:180,ach:1200}[type]||160;o.connect(g);g.connect(audio.destination);o.frequency.setValueAtTime(f,t);o.frequency.exponentialRampToValueAtTime(type==='hit'?55:f*1.4,t+.1);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.045*opt.master*opt.effects,t+.01);g.gain.exponentialRampToValueAtTime(.0001,t+.13);o.start(t);o.stop(t+.14)}catch(e){}}
function show(id,on){$(id).classList.toggle('hidden',!on)}function screen(id){['menu','how','settings','pause','over','stats'].forEach(x=>show(x,x===id))}function toast(t){const e=$('toast');e.textContent=t;e.style.opacity=1;clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.opacity=0,1100)}
function start(){A.games++;Object.assign(S,{state:'play',t:0,score:0,lives:3,combo:0,energy:0,enemies:0,inv:0,shake:0,phase:'TRAINING',event:'',eventT:0,eventNext:28,spawnE:0,spawnN:2.5,spawnP:7,spawnM:0});Object.keys(S.power).forEach(k=>S.power[k]=0);P={x:W/2,y:H/2+20,vx:0,vy:0};enemies=[];energy=[];powers=[];mines=[];parts=[];floats=[];trail=[];drag=null;screen(null);for(let i=0;i<3;i++)spawnEnergy();sound('phase')}
function togglePause(){if(S.state==='play'){S.state='pause';screen('pause')}else if(S.state==='pause'){S.state='play';screen(null);last=performance.now()}}
$('play').onclick=start;$('again').onclick=start;$('resume').onclick=togglePause;$('menuPause').onclick=()=>{S.state='menu';screen('menu')};$('howBtn').onclick=()=>screen('how');$('backHow').onclick=()=>screen('menu');$('settingsBtn').onclick=()=>screen('settings');$('backSettings').onclick=()=>{readSettings();screen('menu')};$('statsBtn').onclick=()=>{updateStats();screen('stats')};$('backStats').onclick=()=>screen('menu');
function bindSettings(){master.value=opt.master;effects.value=opt.effects;shake.checked=opt.shake;motion.checked=opt.motion;contrast.checked=opt.contrast;quality.value=opt.quality;[master,effects,shake,motion,contrast,quality].forEach(e=>e.addEventListener('change',readSettings))}function readSettings(){opt.master=+master.value;opt.effects=+effects.value;opt.shake=shake.checked;opt.motion=motion.checked;opt.contrast=contrast.checked;opt.quality=quality.value;document.body.classList.toggle('contrast',opt.contrast);save()}bindSettings();readSettings();
function hud(){const p=S.t<30?'TRAINING':S.t<60?'RUSH':S.t<120?'CHAOS':'OVERDRIVE';if(p!==S.phase){S.phase=p;toast(p);sound('phase')}$('sc').textContent=Math.floor(S.score);$('bs').textContent=Math.max(A.best,Math.floor(S.score));$('phase').textContent=p;$('lives').textContent='♥ '+S.lives;let st='×'+S.combo;if(S.power.shield)st='🛡 SHIELD';else if(S.power.slow)st='◉ SLOW';else if(S.power.magnet)st='✦ MAGNET';else if(S.power.boost)st='×2 BOOST';else if(S.power.phase)st='◈ PHASE';$('status').textContent=st}
function burst(x,y,c,n=18,sp=180){if(opt.motion)n=Math.floor(n*.45);if(opt.quality==='low')n=Math.min(n,7);else if(opt.quality==='medium')n=Math.min(n,12);for(let i=0;i<n;i++){let a=Math.random()*6.283,v=(.3+Math.random()*.7)*sp;parts.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,l:.5,m:.5,c})}}function float(x,y,t,c,size=17){floats.push({x,y,t,c,size,l:1})}
function spawnEnergy(){for(let k=0;k<20;k++){let x=45+Math.random()*(W-90),y=90+Math.random()*(H-135);if(Math.hypot(x-P.x,y-P.y)>100*U){energy.push({x,y,l:9,a:Math.random()*6});return}}}
const enemyNames=['hunter','fast','dasher','splitter','orbiter'];function spawnEnemy(){let side=Math.floor(Math.random()*4),m=35,x=side===1?W+m:side===3?-m:Math.random()*W,y=side===0?-m:side===2?H+m:Math.random()*H,t=S.t,r=Math.random();let type='hunter';if(t>12&&r<.2)type='fast';if(t>28&&r<.18)type='dasher';if(t>50&&r<.16)type='orbiter';if(t>72&&r<.14)type='splitter';enemies.push({x,y,vx:0,vy:0,warm:1,rot:0,type,orbit:Math.random()<.5?-1:1,dash:.3+Math.random()*.7})}
const powerNames=['shield','slow','magnet','boost','phase'];function spawnPower(){let type=powerNames[Math.floor(Math.random()*powerNames.length)];powers.push({x:65+Math.random()*(W-130),y:100+Math.random()*(H-170),type,t:0,l:10})}function applyPower(k){S.power[k]=k==='boost'?7:6;const n={shield:'SHIELD',slow:'TIME SLOW',magnet:'MAGNET',boost:'2X SCORE',phase:'PHASE SHIFT'}[k];float(P.x,P.y-40,n+' READY',k==='shield'?'#8ffaff':k==='slow'?'#b8a7ff':k==='magnet'?'#ffd84a':k==='boost'?'#7cff9b':'#ff78e8',20);burst(P.x,P.y,'#38f2ff',24,230);sound('power')}
function startEvent(){const ev=['NEON STORM','RED ALERT','ENERGY RAIN','TIME FREEZE','BLACKOUT'][Math.floor(Math.random()*5)];S.event=ev;S.eventT=9;S.eventNext=S.t+28+Math.random()*16;toast(ev);sound('event');if(ev==='ENERGY RAIN')for(let i=0;i<7;i++)spawnEnergy()}
function hit(){if(S.power.shield){S.power.shield=0;S.inv=.8;burst(P.x,P.y,'#8ffaff',25,260);float(P.x,P.y-30,'SHIELD SAVED YOU','#8ffaff');sound('power');return}if(S.inv>0)return;S.lives--;S.inv=1.6;S.combo=0;S.shake=.35;burst(P.x,P.y,'#ff2d55',30,280);float(P.x,P.y-28,'-1 LIFE','#ff2d55',20);sound('hit');if(S.lives<=0)gameOver()}
const ACH=[['first','First Run','Finish one game'],['score100','Century','Score 100+'],['combo20','Combo Master','Reach combo 20'],['survive60','Survivor','Survive 60 seconds'],['energy50','Energy Hunter','Collect 50 energy'],['dodge100','Untouchable','Dodge 100 enemies'],['overdrive','Overdrive','Reach Overdrive']];function checkAch(){let checks={first:A.games>=1,score100:S.score>=100,combo20:S.combo>=20,survive60:S.t>=60,energy50:A.totalEnergy>=50,dodge100:A.totalEnemies>=100,overdrive:S.t>=120};ACH.forEach(a=>{if(checks[a[0]]&&!A.ach[a[0]]){A.ach[a[0]]=1;toast('🏆 '+a[1]);sound('ach')}});save()}
function gameOver(){S.state='over';let fin=Math.floor(S.score),nb=fin>A.best;A.best=Math.max(A.best,fin);A.bestTime=Math.max(A.bestTime,S.t);A.bestCombo=Math.max(A.bestCombo,S.combo);A.totalEnergy+=S.energy;A.totalEnemies+=S.enemies;checkAch();save();$('final').textContent=fin;$('gBest').textContent=A.best;$('gTime').textContent=Math.floor(S.t)+'s';$('gCombo').textContent=S.combo;$('gEnergy').textContent=S.energy;$('summary').textContent='Survived '+Math.floor(S.t)+' seconds · Dodged '+S.enemies+' threats';$('newbest').classList.toggle('hidden',!nb);sound(nb?'combo':'hit');setTimeout(()=>{if(S.state==='over')screen('over')},500)}
function update(dt){S.t+=dt;let pdt=S.event==='TIME FREEZE'?.35:1;dt*=pdt;S.eventT=Math.max(0,S.eventT-dt);if(!S.eventT)S.event='';if(S.t>=S.eventNext)startEvent();if(P.tx!==undefined){let dx=P.tx-P.x,dy=P.ty-P.y,d=Math.hypot(dx,dy)||1,step=(MOBILE?920:720)*Math.max(.82,U)*dt;if(d>1){let k=Math.min(1,step/d);P.x+=dx*k;P.y+=dy*k}}else{let ax=(keys.r?1:0)-(keys.l?1:0),ay=(keys.d?1:0)-(keys.u?1:0),n=Math.hypot(ax,ay)||1,sp=330*U;P.vx+=(ax/n*sp-P.vx)*Math.min(1,dt*14);P.vy+=(ay/n*sp-P.vy)*Math.min(1,dt*14);P.x+=P.vx*dt;P.y+=P.vy*dt}P.x=Math.max(R,Math.min(W-R,P.x));P.y=Math.max(R+52,Math.min(H-R,P.y));if(trail.length<(opt.quality==='low'?10:opt.quality==='medium'?16:25))trail.push({x:P.x,y:P.y,l:.35});S.score+=dt*4*(S.power.boost?2:1);S.inv=Math.max(0,S.inv-dt);S.shake=Math.max(0,S.shake-dt);Object.keys(S.power).forEach(k=>S.power[k]=Math.max(0,S.power[k]-dt));
S.spawnE-=dt;if(S.spawnE<=0&&energy.length<5){spawnEnergy();S.spawnE=.65}for(let i=energy.length-1;i>=0;i--){let e=energy[i];e.l-=dt;e.a+=dt*3;if(e.l<=0){energy.splice(i,1);continue}let dx=P.x-e.x,dy=P.y-e.y,d=Math.hypot(dx,dy)||1;if(S.power.magnet&&d<190){e.x+=dx/d*190*dt;e.y+=dy/d*190*dt}if(d<R+13){energy.splice(i,1);S.energy++;S.score+=10*(S.power.boost?2:1);S.combo++;burst(e.x,e.y,'#38f2ff',12,170);float(e.x,e.y-12,'+'+(S.power.boost?20:10),'#38f2ff');sound('coin');if(S.combo%8===0){S.score+=50;burst(P.x,P.y,'#ffd84a',28,260);float(P.x,P.y-45,'COMBO ×'+S.combo,'#ffd84a',20);sound('combo')}}}
S.spawnP-=dt;if(S.spawnP<=0&&powers.length<1&&S.t>10){spawnPower();S.spawnP=Math.max(7,13-S.t/30)}for(let i=powers.length-1;i>=0;i--){let q=powers[i];q.t+=dt;q.l-=dt;if(q.l<=0){powers.splice(i,1);continue}if(Math.hypot(P.x-q.x,P.y-q.y)<R+18){powers.splice(i,1);applyPower(q.type)}}
let enemyCap=opt.quality==='low'?8:opt.quality==='medium'?10:12;let maxE=Math.min(enemyCap,Math.floor(1+S.t/11)),interval=Math.max(opt.quality==='low'?0.95:.75,3.3-S.t/35);S.spawnN-=dt;if(S.spawnN<=0&&enemies.length<maxE){spawnEnemy();S.spawnN=interval}let extremeSpeed=1+Math.min(S.t/55,2.4);let mobileSpeed=MOBILE?1.18:1;let base=(72+Math.min(S.t,220)*.95)*Math.max(.82,U)*extremeSpeed*mobileSpeed*(S.power.slow?.55:1)*(S.event==='RED ALERT'?1.3:1);for(let i=enemies.length-1;i>=0;i--){let e=enemies[i],dx=P.x-e.x,dy=P.y-e.y,d=Math.hypot(dx,dy)||1,tx=dx/d,ty=dy/d;e.warm=Math.max(0,e.warm-dt);if(e.type==='orbiter'){let ox=-ty*e.orbit,oy=tx*e.orbit;tx=tx*.65+ox*.8;ty=ty*.65+oy*.8}if(e.type==='fast')base*=1.15;if(e.type==='dasher'){e.dash-=dt;if(e.dash<=0){e.dash=.9;let a=Math.atan2(dy,dx);e.vx=Math.cos(a)*base*2.5;e.vy=Math.sin(a)*base*2.5}}else{let f=e.warm>.0?.28:1;e.vx+=(tx*base*f-e.vx)*Math.min(1,dt*4.5);e.vy+=(ty*base*f-e.vy)*Math.min(1,dt*4.5)}for(let j=0;j<enemies.length;j++){if(j===i)continue;let o=enemies[j],sx=e.x-o.x,sy=e.y-o.y,sd=Math.hypot(sx,sy)||.01;if(sd<28){let push=(28-sd)/28*90;e.vx+=(sx/sd)*push*dt;e.vy+=(sy/sd)*push*dt}}e.x+=e.vx*dt;e.y+=e.vy*dt;e.rot=Math.atan2(e.vy,e.vx);if(e.warm<=0&&S.inv<=0&&d<R+12){let split=e.type==='splitter';enemies.splice(i,1);S.enemies++;burst(e.x,e.y,'#ff2d55',20,220);if(split&&enemies.length<12)for(let j=0;j<2;j++){let side=j?1:-1;enemies.push({x:e.x+side*14,y:e.y,vx:side*75,vy:(Math.random()-.5)*45,warm:.45,rot:0,type:'hunter',orbit:1,dash:0})}hit();if(S.state!=='play')return}}
if(S.t>35){S.spawnM-=dt;if(S.spawnM<=0&&mines.length<(opt.quality==='low'?2:3)){mines.push({x:Math.max(70,Math.min(W-70,P.x+(Math.random()-.5)*260)),y:Math.max(100,Math.min(H-70,P.y+(Math.random()-.5)*220)),t:0,rad:60*U});S.spawnM=6}}for(let i=mines.length-1;i>=0;i--){let m=mines[i];m.t+=dt;if(m.t>1.4&&m.t<1.4+dt*2&&Math.hypot(m.x-P.x,m.y-P.y)<m.rad+R)hit();if(m.t>1.8)mines.splice(i,1)}
for(let i=parts.length-1;i>=0;i--){let q=parts[i];q.l-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vx*=.94;q.vy*=.94;if(q.l<=0)parts.splice(i,1)}for(let i=floats.length-1;i>=0;i--){let f=floats[i];f.l-=dt;f.y-=28*dt;if(f.l<=0)floats.splice(i,1)}for(let i=trail.length-1;i>=0;i--){trail[i].l-=dt;if(trail[i].l<=0)trail.splice(i,1)}checkAch();hud()}
function glow(c,b){if(opt.quality==='low'){ctx.shadowColor='transparent';ctx.shadowBlur=0;return}ctx.shadowColor=c;ctx.shadowBlur=b}function draw(now){ctx.fillStyle='#050713';ctx.fillRect(0,0,W,H);if(S.shake>0&&opt.shake&&!opt.motion)ctx.translate((Math.random()-.5)*10*S.shake*3,(Math.random()-.5)*10*S.shake*3);let g=opt.quality==='low'?64:48,off=(now/60)%g;ctx.strokeStyle='rgba(56,242,255,.065)';ctx.beginPath();for(let x=-g+off;x<W+g;x+=g){ctx.moveTo(x,0);ctx.lineTo(x,H)}for(let y=-g+off;y<H+g;y+=g){ctx.moveTo(0,y);ctx.lineTo(W,y)}ctx.stroke();ctx.fillStyle='rgba(56,242,255,.2)';for(let a of amb){a.y-=a.s*.0004;if(a.y<0)a.y=1;ctx.beginPath();ctx.arc(a.x*W,a.y*H,a.r,0,6.283);ctx.fill()}if(S.event==='NEON STORM'){ctx.strokeStyle='rgba(56,242,255,.18)';for(let i=0;i<(opt.quality==='low'?3:7);i++){ctx.beginPath();ctx.moveTo(Math.random()*W,0);ctx.lineTo(Math.random()*W,H);ctx.stroke()}}if(S.event==='BLACKOUT')ctx.fillStyle='rgba(0,0,8,.52)',ctx.fillRect(0,0,W,H);
for(let q of powers){let c={shield:'#8ffaff',slow:'#b8a7ff',magnet:'#ffd84a',boost:'#7cff9b',phase:'#ff78e8'}[q.type];glow(c,20);ctx.strokeStyle=c;ctx.lineWidth=2;ctx.beginPath();ctx.arc(q.x,q.y,16+Math.sin(q.t*5)*2,0,6.283);ctx.stroke();ctx.fillStyle=c;ctx.font='900 9px Orbitron';ctx.textAlign='center';ctx.fillText({shield:'S',slow:'T',magnet:'M',boost:'2X',phase:'P'}[q.type],q.x,q.y+3)}for(let e of energy){let s=13+Math.sin(e.a)*2;glow('#38f2ff',18);ctx.fillStyle='#38f2ff';ctx.beginPath();ctx.moveTo(e.x,e.y-s);ctx.lineTo(e.x+s*.7,e.y);ctx.lineTo(e.x,e.y+s);ctx.lineTo(e.x-s*.7,e.y);ctx.fill()}for(let m of mines){ctx.strokeStyle='rgba(255,45,85,.6)';ctx.setLineDash([5,5]);ctx.beginPath();ctx.arc(m.x,m.y,m.rad,0,6.283);ctx.stroke();ctx.setLineDash([])}for(let e of enemies){ctx.save();ctx.translate(e.x,e.y);ctx.rotate(e.rot);let c={hunter:'#ff2d55',fast:'#ff8a3d',dasher:'#ffb43d',splitter:'#ff4f9a',orbiter:'#b86cff'}[e.type];glow(c,18);ctx.fillStyle=c;if(e.type==='orbiter'){ctx.beginPath();ctx.arc(0,0,11,0,6.283);ctx.strokeStyle=c;ctx.lineWidth=4;ctx.stroke()}else if(e.type==='splitter'){ctx.fillRect(-10,-10,20,20)}else{ctx.beginPath();ctx.moveTo(15,0);ctx.lineTo(-10,10);ctx.lineTo(-5,0);ctx.lineTo(-10,-10);ctx.fill()}ctx.restore()}for(let t of trail){ctx.fillStyle='rgba(56,242,255,'+t.l*.5+')';ctx.beginPath();ctx.arc(t.x,t.y,R*(.4+t.l),0,6.283);ctx.fill()}if(S.state!=='over'){glow(S.power.shield?'#8ffaff':'#38f2ff',S.power.shield?36:26);ctx.fillStyle=S.power.shield?'#8ffaff':'#38f2ff';ctx.beginPath();ctx.arc(P.x,P.y,R,0,6.283);ctx.fill();glow('transparent',0);ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(P.x,P.y,R*.52,0,6.283);ctx.fill()}for(let p of parts){ctx.globalAlpha=Math.max(0,p.l/p.m);ctx.fillStyle=p.c;ctx.fillRect(p.x-2,p.y-2,4,4)}ctx.globalAlpha=1;for(let f of floats){ctx.globalAlpha=Math.min(1,f.l*1.5);ctx.font='800 '+f.size+'px Orbitron';ctx.textAlign='center';ctx.fillStyle=f.c;ctx.fillText(f.t,f.x,f.y)}ctx.globalAlpha=1}
function updateStats(){$('stBest').textContent=A.best;$('stTime').textContent=Math.floor(A.bestTime)+'s';$('stCombo').textContent=A.bestCombo;$('stEnergy').textContent=A.totalEnergy;$('stEnemies').textContent=A.totalEnemies;$('stGames').textContent=A.games;$('achievements').innerHTML=ACH.map(a=>'<div class="'+(A.ach[a[0]]?'':'locked')+'">'+(A.ach[a[0]]?'🏆':'🔒')+' <b>'+a[1]+'</b> — '+a[2]+'</div>').join('')}
function loop(now){let dt=Math.min(.05,(now-last)/1000);last=now;if(S.state==='play')update(dt);draw(now);requestAnimationFrame(loop)}P.x=W/2;P.y=H/2;hud();requestAnimationFrame(loop);
})();
